const PRODUCT_ACTION_TYPES = {
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_ERROR: 'CREATE_PRODUCT_ERROR',
};

export default PRODUCT_ACTION_TYPES;
