const TODO_ACTION_TYPES = {
  ADD_TASK_ACTION: 'ADD_TASK_ACTION',
  UPDATE_TASK_ACTION: 'UPDATE_TASK_ACTION',
  DONE_TASK_ACTION: 'DONE_TASK_ACTION',
  REMOVE_TASK_ACTION: 'REMOVE_TASK_ACTION',
};

export default TODO_ACTION_TYPES;
